{{- if and .Values.mintAgent.enabled .Values.mintAgent.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mint-agent.name" . }}
  namespace: {{ include "runs-namespace" . }}
  labels:
    {{- include "mint-agent.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mint-agent.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mint-agent.name" . }}
    namespace: {{ include "main-namespace" . }}
{{- end }}
