{{- if and .Values.mintAgent.enabled .Values.mintAgent.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mint-agent.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "mint-agent.labels" . | nindent 4 }}
  {{- with (include "mint-agent.service-account-annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
