{{- if .Values.mintAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mint-agent.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "mint-agent.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mint-agent.selector-labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mint-agent.selector-labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mint-agent.service-account-name" . }}
      securityContext:
        {{- toYaml .Values.mintAgent.securityContext | nindent 8 }}
      {{- with .Values.mintAgent.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: {{ include "mint-agent.name" . }}
          securityContext:
            {{- toYaml .Values.mintAgent.containers.mintAgent.securityContext | nindent 12 }}
          image: "{{ .Values.mintAgent.image.repository }}:{{ .Values.mintAgent.image.tag }}"
          imagePullPolicy: {{ .Values.mintAgent.image.pullPolicy }}
          env:
            - name: HELM_VERSION
              value: {{ include "compute-plane.chart" . }}
            - name: ENABLE_STATIC_MODE
              value: "true"
            - name: RUNS_NAMESPACE
              value: {{ include "runs-namespace" . }}
            - name: MINT_ADDR
              value: {{ .Values.controlPlane.mintAddress }}
            - name: MORC_ADDR
              value: {{ .Values.controlPlane.morcAddress }}
            - name: JWT_FILEPATH
              value: /mnt/jwtRefresh/accessToken
            {{- if .Values.localDevelopment.enabled }}
            - name: LOCAL
              value: "true"
            {{- end }}
          resources:
            {{- toYaml .Values.mintAgent.containers.mintAgent.resources | nindent 12 }}
          volumeMounts:
            - name: service-jwt
              mountPath: /mnt/jwtRefresh
            {{- if .Values.localDevelopment.enabled }}
            - name: local-mcloud
              mountPath: /go/mcloud
            - name: local-go-build-cache
              mountPath: /root/.cache
            - name: local-go-pkg-cache
              mountPath: /go/pkg
            {{- end }}
          {{- if .Values.localDevelopment.enabled }}
          command: ["go", "run", "mint_agent/cmd/main.go"]
          workingDir: /go/mcloud
          {{- end }}
      volumes:
        {{- if .Values.localDevelopment.enabled }}
        - name: local-mcloud
          hostPath:
            path: /mcloud
        - name: local-go-build-cache
          hostPath:
            path: /go-build-cache
        - name: local-go-pkg-cache
          hostPath:
            path: /go-pkg-cache
        {{- end }}
        - name: service-jwt
          secret:
            secretName: {{ include "compute-plane.service-jwt.name" . }}
      {{- with .Values.mintAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mintAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mintAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
