apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "worker.selector-labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "worker.selector-labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "worker.service-account-name" . }}
      securityContext:
        {{- toYaml .Values.worker.securityContext | nindent 8 }}
      {{- with .Values.worker.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.containers.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: HELM_VERSION
              value: {{ include "compute-plane.chart" . }}
            - name: MORC_ADDR
              value: {{ .Values.controlPlane.morcAddress }}
            - name: MAPI_ADDR
              value: {{ .Values.controlPlane.mapiAddress }}
            - name: MLOG_ADDR
              value: {{ .Values.controlPlane.mlogAddress }}
            - name: MINT_ADDR
              value: {{ .Values.controlPlane.mintAddress }}
            - name: RUNS_NAMESPACE
              value: {{ include "runs-namespace" . }}
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "compute-plane.service-api-key.name" . }}
                  key: serviceApiKey
            - name: RUNS_SERVICE_ACCOUNT_NAME
              value: {{ include "runs.service-account-name" . }}
            - name: DEPLOYMENT_ENV
              value: {{ .Values.env }}
            - name: JWT_FILEPATH
              value: /mnt/jwtRefresh/accessToken
            - name: DISABLE_MLOG_AGENT
              value: {{ not .Values.worker.enableRunLogging | quote }}
            - name: DISABLE_MINT_AGENT
              value: {{ not .Values.worker.enableRunInteractivity | quote }}
            {{- include "compute-plane.imagePullSecretsEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.containers.worker.resources | nindent 12 }}
          volumeMounts:
            - name: service-jwt
              mountPath: /mnt/jwtRefresh
      volumes:
        - name: service-jwt
          secret:
            secretName: {{ include "compute-plane.service-jwt.name" . }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
